In [162]:
import numpy as np


In [171]:
def quicksort(arr, l, r):

    if l >= r:
        return 
    start = l
    end = r
    p_idx = (l + r)//2
    p = arr[p_idx]
    print(arr)
    while l <=r:
        while arr[l] < p:
            l += 1
        while arr[r] > p :
            r -= 1
        if l <= r:
            arr[l], arr[r] = arr[r], arr[l]
            l +=1
            r -=1
    quicksort(arr,start, r)
    quicksort(arr, l, end)

In [172]:
arr =np.random.randint(0, 20, 10)
print(arr)
print("sorted")
quicksort(arr, 0, len(arr)-1)
print(arr)

[17  2  6 15  8 13  4 12 19 13]
sorted
[17  2  6 15  8 13  4 12 19 13]
[ 4  2  6  8 15 13 17 12 19 13]
[ 2  4  6  8 15 13 17 12 19 13]
[ 2  4  6  8 15 13 17 12 19 13]
[ 2  4  6  8 15 13 13 12 19 17]
[ 2  4  6  8 12 13 13 15 19 17]
[ 2  4  6  8 12 13 13 15 19 17]
[ 2  4  6  8 12 13 13 15 19 17]
[ 2  4  6  8 12 13 13 15 17 19]


In [ ]:
def quicksort(arr, l, r):
    if l >= r:  # Base case: subarray of size 0 or 1
        return

    # Choose the pivot (middle element)
    pivot = arr[(l + r) // 2]
    print(f"Pivot: {pivot}")
    
    # Partitioning
    i, j = l, r
    while i <= j:
        # Find elements on the wrong side of the pivot
        while arr[i] < pivot:
            i += 1
        while arr[j] > pivot:
            j -= 1
        
        if i <= j:
            # Swap elements
            arr[i], arr[j] = arr[j], arr[i]
            i += 1
            j -= 1

    # Recursive calls for left and right subarrays
    quicksort(arr, l, j)
    quicksort(arr, i, r)

# Example usage
arr = [3, 6, 8, 10, 1, 2, 1]
print("Original array:", arr)
quicksort(arr, 0, len(arr) - 1)
print("Sorted array:", arr)

In [1]:
0.95**4 * (0.95 +1 - 0.95**2)

0.8531952968749997

In [2]:
1 - 0.95**4 * (0.95 +1 - 0.95**2)

0.14680470312500027